### ISSUE TITLE
installatie sf package op de HPC

### ISSUE THREAD

**Issue by slambrechts** [inbo/mbag-bodem#21]
installatie `sf `package lukt niet op HPC:

**Oorzaak**:

installatie dependency package `units `lukt niet

Hans: `libudunits2-dev` `libgdal-dev` `libgeos-dev` `libproj-dev` zijn de dependencies die je moet installeren voor sf package

Sam: is dit package enkel nodig voor de kaart van Vlaanderen voor de visualisatie van de staalname locaties? Hans: ja, voorlopig wel

**Comment by nick-dil** [comment]
Hello,
On the HPC you should prioritize using the pre-installed bundles instead of installing everything by yourself. This allows us all to work with the same packages and versions. For example:
```
module load R-bundle-Bioconductor/3.19-foss-2023b-R-4.4.1
```
This bundel contains a lot of packages we already use like `phyloseq` , `ggplot2` , `vegan`, etc .... and also `sf` !

So I can get this on the HPC :

![image](https://github.com/user-attachments/assets/8a05e089-9efd-4ed2-82ad-3173c616f2fb)

**Comment by slambrechts** [comment]
that would have saved me a lot of headache ([issue132](https://github.com/slambrechts/INBO_eDNA_metabarcoding_BODEM/issues/132)) :) I created a (bad) habit of installing everything myself, because in the past many of the tools, especially the ones for shotgun metagenomics were not installed on the HPC and it sometimes took months for them to install a requested tool
